---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Mission Life New User Email Invitation
Resources:

# SQS Resources 
  MissionLifeAllUsersDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 172800
      QueueName: MissionLifeAllUsersDeadLetter
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 300
  MissionLifeAllUsersQueue:
    DependsOn:
      - MissionLifeAllUsersDeadLetterQueue
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 172800
      QueueName: MissionLifeAllUsers
      ReceiveMessageWaitTimeSeconds: 0
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MissionLifeAllUsersDeadLetterQueue.Arn
        maxReceiveCount: 3
      VisibilityTimeout: 300

# Lambda Resources
  MissionLifeAllUsersSchedulerLambda:
    DependsOn:
      - MissionLifeAllUsersSchedulerLambdaExecutionRole
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/mission-life-all-users-scheduler.zip
      FunctionName: missionLifeAllUsersScheduler
      Handler: index.handler
      MemorySize: 256
      Role: !GetAtt MissionLifeAllUsersSchedulerLambdaExecutionRole.Arn
      Runtime: nodejs12.x
      Timeout: 300
      Environment:
        Variables:
          REACH_BASE_URL: {{{REACH_BASE_URL}}}
          REACH_AUTHORIZATION_TOKEN: {{{REACH_AUTHORIZATION_TOKEN}}}
          MISSION_LIFE_ALL_USERS_QUEUE_URL: {{{MISSION_LIFE_ALL_USERS_QUEUE_URL}}}

  MissionLifeAllUsersSchedulerLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: '/'
      Policies:
      - PolicyName: logs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
      - PolicyName: sqs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - sqs:*
            Resource: 
              - !GetAtt MissionLifeAllUsersQueue.Arn
              - !GetAtt MissionLifeAllUsersDeadLetterQueue.Arn

  MissionLifeAllUsersSchedulerLambdaLogGroup:
    DependsOn: MissionLifeAllUsersSchedulerLambda
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 14
      LogGroupName: !Join
        - ''
        - - 'lambda/'
          - !Ref MissionLifeAllUsersSchedulerLambda

# - PolicyName: dynamodb
#   PolicyDocument:
#     Statement:
#     - Effect: Allow
#       Action:
#       - dynamodb:GetItem
#       - dynamodb:GetRecords
#       - dynamodb:BatchGetItem
#       - dynamodb:DescribeTable
#       - dynamodb:Query
#       - dynamodb:Scan
#       - dynamodb:PutItem
#       Resource:
#       - !GetAtt CoverageReportsTable.Arn
# New User Scheduler Dynamo Resources
# WebAppUsersTable:
#   Type: AWS::DynamoDB::Table
#   Properties:
#     TableName: "WEB_APP_USERS"
#     AttributeDefinitions:
#       -
#         AttributeName: "SEARCH_ID"
#         AttributeType: "S"
#       -
#         AttributeName: "END_DATE"
#         AttributeType: "S"
#     KeySchema:
#       -
#         AttributeName: "SEARCH_ID"
#         KeyType: "HASH"
#     GlobalSecondaryIndexes:
#       -
#         IndexName: "END_DATE_GSI"
#         KeySchema:
#           -
#           AttributeName: "END_DATE"
#           KeyType: "HASH"
#         Projection:
#           ProjectionType: "ALL"
#     BillingMode: "PAY_PER_REQUEST"
# New User Scheduler Cloudwatch & Alarm Resources	
# MissionLifeAllUsersSchedulerRule:
#   Type: AWS::Events::Rule
#   Properties:
#     ScheduleExpression: "cron(00 13 * * ? *)"
#     Targets:
#     - Id: MissionLifeAllUsersSchedulerRuleTarget
#     Arn: !GetAtt MissionLifeAllUsersSchedulerLambda.Arn
# MissionLifeAllUsersSchedulerInvokePermission:
#   Type: AWS::Lambda::Permission
#   Properties:
#     FunctionName: !GetAtt MissionLifeAllUsersSchedulerLambda.Arn
#     Action: "lambda:InvokeFunction"
#     Principal: "events.amazonaws.com"
#     SourceArn: !GetAtt MissionLifeAllUsersSchedulerRule.Arn